/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_cedva;



import Modelo.E_GRUPOS;
import Modelo.E_MATERIAS;
import Modelo.E_MATERIA_GRUPO;
import Mysql.MySqlConnect;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author P3DR1TO
 */
public class Buscar_MateriasCE extends javax.swing.JFrame {
    ArrayList<E_MATERIA_GRUPO> mat_group= new ArrayList<E_MATERIA_GRUPO>();
    ArrayList<E_MATERIAS> materias= new ArrayList<E_MATERIAS>();
    ArrayList<E_GRUPOS> grupos= new ArrayList<E_GRUPOS>();
    int ID_GRUPO;
    int ID_MATERIA;
    int NB_MATERIA;
    int ID_GRUPO_MATERIA;
    Control_Escolar ce;

    
        public Buscar_MateriasCE(int ID_GRUPO, int ID_MATERIA)
    {
        initComponents();
        this.setLocationRelativeTo(null); 
   
    }

        
    public Buscar_MateriasCE() {
        initComponents();
        this.setLocationRelativeTo(null);  
        loadData();
    }
    
    public Buscar_MateriasCE(Control_Escolar ce) {
        initComponents();
        this.setLocationRelativeTo(null);  
        this.ce=ce;
        loadData();
    }
    
 
    
    public void loadData(){
        
         mat_group.clear();
         ID_GRUPO_MATERIA=0;
        
               MySqlConnect mysqlConnect = new MySqlConnect();
//   Statement st;
   PreparedStatement st = null ;

        try {
//            st = mysqlConnect.connect().createStatement();

          String sql = "";
          

           sql = "SELECT a.ID_GRUPO_MATERIA, a.ID_GRUPO, a.ID_MATERIA, b.CL_GRUPO, c.NB_MATERIA FROM k_grupo_materia a\n" +
"INNER JOIN c_grupo b on b.ID_GRUPO=a.ID_GRUPO\n" +
"inner JOIN c_materia c on c.ID_MATERIA = a.ID_MATERIA;";
        st =mysqlConnect.connect().prepareStatement(sql);

          
         
          
          


ResultSet rs = st.executeQuery();
while(rs.next()) { 
 int idMat_Gpo = rs.getInt("ID_GRUPO_MATERIA");  
 int idGrupo = rs.getInt("ID_GRUPO");  
 int idMateria = rs.getInt("ID_MATERIA");  
 String clGrupo = rs.getString("CL_GRUPO");  
 String nbMateria = rs.getString("NB_MATERIA"); 

 mat_group.add(new E_MATERIA_GRUPO(idMat_Gpo,idGrupo,idMateria,clGrupo,nbMateria));
 
}
        } catch (SQLException ex) {
            Logger.getLogger(Buscar_MateriasCE.class.getName()).log(Level.SEVERE, null, ex);
        }
        

mysqlConnect.disconnect();
String col[] = {"Id","Grupo","Materia"};
    DefaultTableModel dtm = new DefaultTableModel(col, 0);
    for (E_MATERIA_GRUPO s : mat_group) {
         Object[] objs = {s.getID_GRUPO_MATERIA(),s.getCL_GRUPO(),s.getNB_MATERIA()};
         dtm.addRow( objs);
    }

   
    jTable1.setModel(dtm);
       jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
       
    jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
    jTable1.getColumnModel().getColumn(0).setMinWidth(0);
    jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
     private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        
        // get the model from the jtable
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        // get the selected row index
       int selectedRowIndex = jTable1.getSelectedRow();
        // set the selected row data into jtextfields
       ID_GRUPO_MATERIA =Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString()) ;   
         for (E_MATERIA_GRUPO e_materia_grupo : mat_group) {
             if(e_materia_grupo.getID_GRUPO_MATERIA()==ID_GRUPO_MATERIA)
             {
                  ID_GRUPO = e_materia_grupo.getID_GRUPO();
                  ID_MATERIA= e_materia_grupo.getID_MATERIA();
                  NB_MATERIA= e_materia_grupo.getID_MATERIA();
                  break;
             }
         }

    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_selecc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Grupo", "Materia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        btn_selecc.setText("Seleccionar");
        btn_selecc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_selecc)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_selecc)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
//         Menu m= new Menu();
//               m.setLocationRelativeTo(null);
//                m.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btn_seleccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccActionPerformed
        if(ID_MATERIA!=0)
        {
            //        APP_CONTEXTO.setNB_PROSPECTO(NB_PROSPECTO);
            //        APP_CONTEXTO.setID_PROSPECTO(ID_PROSPECTO);
            ce.setEditMateria(NB_MATERIA);
            ce.setIdMateria(ID_MATERIA);
//            as.setClGrupo(CL_GRUPO);
//            as.setIdGrupos(ID_GRUPO);
            dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));

        }
        else
        {
         Icon image= new ImageIcon(getClass().getResource("/imagenes/selecciona_sin_f.png"));
            JOptionPane.showMessageDialog(null, "Selecciona una materia","",JOptionPane.INFORMATION_MESSAGE,image);
            
        }
    }//GEN-LAST:event_btn_seleccActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_selecc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
