/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_cedva;

import Modelo.E_MATERIAS;
import Mysql.MySqlConnect;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author P3DR1TO
 */
public class Buscar_Materia extends javax.swing.JFrame {
    
    ArrayList<E_MATERIAS> materias= new ArrayList<E_MATERIAS>();
    int ID_MATERIA = 0;
    String NB_MATERIA;
    Asignar_Materia as;
    /**
     * Creates new form Usuarios
     */
    public Buscar_Materia(Asignar_Materia as) {
        initComponents();
        this.as=as;
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Logo_JAR.png")).getImage());
        this.getContentPane().setBackground(Color.RED);
        this.setLocationRelativeTo(this);
        loadData();
    }
    
    
    public void loadData()
    {
        materias.clear();
        ID_MATERIA=0;
        
        MySqlConnect mysqlConnect = new MySqlConnect();
        Statement st;
        try {
            st = mysqlConnect.connect().createStatement();

        String sql = "SELECT * FROM c_materia";
        ResultSet rs = st.executeQuery(sql);
        while(rs.next()) { 
        int idMateria = rs.getInt("ID_MATERIA"); 
        String clMateria = rs.getString("CL_MATERIA");
        String nbMateria = rs.getString("NB_MATERIA");
        materias.add(new E_MATERIAS(idMateria, clMateria, nbMateria));
        }
            } catch (SQLException ex) {
            Logger.getLogger(Buscar_Materia.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        mysqlConnect.disconnect();
        String col[] = {"Id","Clave","Materia"};
        DefaultTableModel dtm = new DefaultTableModel(col, 0);
         for (E_MATERIAS s : materias) {
         Object[] objs = {s.getID_MATERIA(),s.getCL_MATERIA(),s.getNB_MATERIA()};
         dtm.addRow( objs);
         }
         
        jTableM.setModel(dtm);
        jTableM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTableM.getColumnModel().getColumn(0).setMaxWidth(0);

        jTableM.getColumnModel().getColumn(0).setMinWidth(0);

        jTableM.getColumnModel().getColumn(0).setPreferredWidth(0);

        jTableM.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTableM.getColumnModel().getColumn(2).setPreferredWidth(400);
    }

        private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        
        // get the model from the jtable
       DefaultTableModel model = (DefaultTableModel)jTableM.getModel();
        // get the selected row index
       int selectedRowIndex = jTableM.getSelectedRow();
        // set the selected row data into jtextfields
       ID_MATERIA =Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString()) ; 
       NB_MATERIA =model.getValueAt(selectedRowIndex, 2).toString();

    }   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_selecc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableM = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 505));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_selecc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_selecc.setText("Seleccionar");
        btn_selecc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccActionPerformed(evt);
            }
        });
        getContentPane().add(btn_selecc, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, -1, -1));

        jTableM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Clave", "Materia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableM.setEditingRow(1);
        jTableM.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableM.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableM);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 790, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    
    }//GEN-LAST:event_formWindowClosed

    private void btn_seleccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccActionPerformed
        if(ID_MATERIA!=0)
        {

            as.setNbMateria(NB_MATERIA);
            as.setIdMateria(ID_MATERIA);
            dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));

        }
        else
        {
         Icon image= new ImageIcon(getClass().getResource("/imagenes/selecciona_sin_f.png"));
            JOptionPane.showMessageDialog(null, "Selecciona una materia","",JOptionPane.INFORMATION_MESSAGE,image);
            
        }
    }//GEN-LAST:event_btn_seleccActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_selecc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableM;
    // End of variables declaration//GEN-END:variables
}
