/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_cedva;


import Modelo.E_CARRERAS;
import Mysql.MySqlConnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;


/**
 *
 * @author P3DR1TO
 */
public class Carrera extends javax.swing.JFrame {
    
    ArrayList<E_CARRERAS> carreras= new ArrayList<E_CARRERAS>();
    int ID_CARRERA = 0;
    /**
     * Creates new form Usuarios
     */
    public Carrera() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Logo_JAR.png")).getImage());
        this.getContentPane().setBackground(Color.RED);
        this.setLocationRelativeTo(this);
        loadData();
    }
    
    
    public void loadData()
    {
        carreras.clear();
        ID_CARRERA=0;
        
        MySqlConnect mysqlConnect = new MySqlConnect();
        Statement st;
        try {
            st = mysqlConnect.connect().createStatement();

        String sql = "SELECT * FROM c_carrera";
        ResultSet rs = st.executeQuery(sql);
        while(rs.next()) { 
        int idCarrera= rs.getInt("ID_CARRERA"); 
        String clCarrera = rs.getString("CL_CARRERA");
        String nbCarrera = rs.getString("NB_CARRERA");
        carreras.add(new E_CARRERAS(idCarrera, clCarrera, nbCarrera));
        }
            } catch (SQLException ex) {
            Logger.getLogger(Carrera.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        mysqlConnect.disconnect();
        String col[] = {"Id","Clave","Carrera"};
        DefaultTableModel dtm = new DefaultTableModel(col, 0);
         for (E_CARRERAS s : carreras) {
         Object[] objs = {s.getID_CARRERA(),s.getCL_CARRERA(),s.getNB_CARRERA()};
         dtm.addRow( objs);
         }
         
        jTableCa.setModel(dtm);
        jTableCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTableCa.getColumnModel().getColumn(0).setMaxWidth(0);

        jTableCa.getColumnModel().getColumn(0).setMinWidth(0);

        jTableCa.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        jTableCa.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTableCa.getColumnModel().getColumn(2).setPreferredWidth(400);
    }
    
     private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        
        // get the model from the jtable
       DefaultTableModel model = (DefaultTableModel)jTableCa.getModel();
        // get the selected row index
       int selectedRowIndex = jTableCa.getSelectedRow();
        // set the selected row data into jtextfields
       ID_CARRERA =Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString()) ;       

    }   
     
     public void clear(){
            txtClCarrera.setText(null);
            txtNbCarrera.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_agregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCa = new javax.swing.JTable();
        txtClCarrera = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNbCarrera = new javax.swing.JTextField();
        btn_atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(820, 400));
        setMinimumSize(new java.awt.Dimension(820, 400));
        setPreferredSize(new java.awt.Dimension(820, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_agregar.setText("Guardar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        jTableCa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Clave", "Carrera"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCa.setEditingRow(1);
        jTableCa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableCa.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableCa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 200));

        txtClCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClCarreraActionPerformed(evt);
            }
        });
        getContentPane().add(txtClCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Clave Carrera:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Carrera:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        getContentPane().add(txtNbCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 490, -1));

        btn_atras.setText("Regresar");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtClCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClCarreraActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if (txtClCarrera.getText().equals("") && txtNbCarrera.getText().equals(""))
            {    JOptionPane.showMessageDialog(rootPane, "Debes agregar una clave y una carrera", "MENSAJE DE ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        else if (txtClCarrera.getText().equals(""))
            {    JOptionPane.showMessageDialog(rootPane, "Debes agregar una clave para la carrera", "MENSAJE DE ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        else if (txtNbCarrera.getText().equals(""))
            {    JOptionPane.showMessageDialog(rootPane, "Debes agregar una carrera", "MENSAJE DE ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        else if(!txtClCarrera.getText().equals("") && !txtNbCarrera.getText().equals("")){  
        try {
            // agregar
            // the mysql insert statement
            MySqlConnect mysqlConnect = new MySqlConnect();
            String query="";
            String message="";
            if(ID_CARRERA==0)
            {
                message="Se agrego una carrera";
                query = " insert into c_carrera (CL_CARRERA, NB_CARRERA)"
                    + " values (?, ?)";
                
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = mysqlConnect.connect().prepareStatement(query);
            preparedStmt.setString (1, txtClCarrera.getText());
            preparedStmt.setString (2, txtNbCarrera.getText());
            // execute the preparedstatement
            preparedStmt.execute();
            clear();
            }
            else 
            {
                message="Se edito la carrera seleccionada";

                query = "update c_carrera set NB_CARRERA = ? where ID_CARRERA = ?";
                PreparedStatement preparedStmt = mysqlConnect.connect().prepareStatement(query);
                preparedStmt.setString(1, txtNbCarrera.getText());             
                preparedStmt.setInt(2, ID_CARRERA);
                 // execute the java preparedstatement
                 preparedStmt.executeUpdate();
                 clear();
                 txtClCarrera.enable(true);
            }
            loadData();
            Icon image= new ImageIcon(getClass().getResource("/imagenes/correcto_sin_f.png"));
            JOptionPane.showMessageDialog(rootPane, message,"",JOptionPane.INFORMATION_MESSAGE,image);
            mysqlConnect.connect().close();
        } catch (SQLException ex) {
            Logger.getLogger(Carrera.class.getName()).log(Level.SEVERE, null, ex);
        }
             }
         else 
        {
           
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(ID_CARRERA!=0)
        {
            for (E_CARRERAS carr : carreras) {
                if(carr.getID_CARRERA()==ID_CARRERA)
                {
                    txtClCarrera.enable(false);
                    txtClCarrera.setText(carr.getCL_CARRERA());                    
                    txtNbCarrera.setText(carr.getNB_CARRERA());
                    break;
                }
            }
        }
        else 
        {
        Icon image= new ImageIcon(getClass().getResource("/imagenes/selecciona_sin_f.png"));
        JOptionPane.showMessageDialog(null, "Selecciona una carrera","",JOptionPane.INFORMATION_MESSAGE,image);
        }
   
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        Menu refresh= new Menu();
//        refresh.setVisible(true);
        refresh.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(ID_CARRERA!=0)
            {
    int dialogButton = JOptionPane.YES_NO_OPTION;
    int dialogResult = JOptionPane.showConfirmDialog(this, "¿Desea eliminar la carrera que seleccionaste?, Este proceso no se puede deshacer.", "Confirmar", dialogButton);
    if(dialogResult == 0) {
//  System.out.println("Yes option");
        try {
            MySqlConnect mysqlConnect = new MySqlConnect();
            String query="";
            String message="";
            
                   query = "delete from c_carrera where ID_CARRERA = ?";
                  message="Se elimino la Carrera";

                PreparedStatement preparedStmt = mysqlConnect.connect().prepareStatement(query);
                preparedStmt.setInt(1, ID_CARRERA);
                preparedStmt.execute();

            loadData();
            Icon image= new ImageIcon(getClass().getResource("/imagenes/borrar_sin_f.png"));
            JOptionPane.showMessageDialog(null, message,"",JOptionPane.INFORMATION_MESSAGE,image);
            mysqlConnect.connect().close();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
}
            }
            else 
            {
            Icon image= new ImageIcon(getClass().getResource("/imagenes/selecciona_sin_f.png"));
            JOptionPane.showMessageDialog(null, "Selecciona una carrera","",JOptionPane.INFORMATION_MESSAGE,image);
            }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Menu m= new Menu();
               m.setLocationRelativeTo(null);
                m.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCa;
    private javax.swing.JTextField txtClCarrera;
    private javax.swing.JTextField txtNbCarrera;
    // End of variables declaration//GEN-END:variables
}
