/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_cedva;

import Modelo.E_MATERIAS;
import Mysql.MySqlConnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author P3DR1TO
 */
public class Materias extends javax.swing.JFrame {
    
    ArrayList<E_MATERIAS> materias= new ArrayList<E_MATERIAS>();
    int ID_MATERIA = 0;
    /**
     * Creates new form Usuarios
     */
    public Materias() {
        initComponents();
        this.getContentPane().setBackground(Color.RED);
        this.setLocationRelativeTo(this);
        loadData();
    }
    
    
    public void loadData()
    {
        materias.clear();
        ID_MATERIA=0;
        
        MySqlConnect mysqlConnect = new MySqlConnect();
        Statement st;
        try {
            st = mysqlConnect.connect().createStatement();

        String sql = "SELECT * FROM c_materia";
        ResultSet rs = st.executeQuery(sql);
        while(rs.next()) { 
        int idMateria = rs.getInt("ID_MATERIA"); 
        String clMateria = rs.getString("CL_MATERIA");
        String nbMateria = rs.getString("NB_MATERIA");
        materias.add(new E_MATERIAS(idMateria, clMateria, nbMateria));
        }
            } catch (SQLException ex) {
            Logger.getLogger(Materias.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        mysqlConnect.disconnect();
        String col[] = {"Id","Clave","Materia"};
        DefaultTableModel dtm = new DefaultTableModel(col, 0);
         for (E_MATERIAS s : materias) {
         Object[] objs = {s.getID_MATERIA(),s.getCL_MATERIA(),s.getNB_MATERIA()};
         dtm.addRow( objs);
         }
         
        jTableM.setModel(dtm);
        jTableM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTableM.getColumnModel().getColumn(0).setMaxWidth(0);

        jTableM.getColumnModel().getColumn(0).setMinWidth(0);

        jTableM.getColumnModel().getColumn(0).setPreferredWidth(0);

        jTableM.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTableM.getColumnModel().getColumn(2).setPreferredWidth(400);
    }

        private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        
        // get the model from the jtable
       DefaultTableModel model = (DefaultTableModel)jTableM.getModel();
        // get the selected row index
       int selectedRowIndex = jTableM.getSelectedRow();
        // set the selected row data into jtextfields
       ID_MATERIA =Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString()) ;       

    }   

     public void clear(){
            txtClMateria.setText(null);
            txtNbMateria.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_agregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableM = new javax.swing.JTable();
        txtClMateria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNbMateria = new javax.swing.JTextField();
        btn_atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 505));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_agregar.setText("Guardar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        jTableM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Clave", "Materia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableM.setEditingRow(1);
        jTableM.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableM.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableM);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 790, 400));

        txtClMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(txtClMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Clave Materia:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Materia:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));
        getContentPane().add(txtNbMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 490, -1));

        btn_atras.setText("Regresar");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtClMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClMateriaActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        
        if (txtClMateria.getText().equals("") && txtNbMateria.getText().equals(""))
            {    JOptionPane.showMessageDialog(rootPane, "Debes agregar una clave y una materia", "MENSAJE DE ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        else if (txtClMateria.getText().equals(""))
            {    JOptionPane.showMessageDialog(rootPane, "Debes agregar una clave para la materia", "MENSAJE DE ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        else if (txtNbMateria.getText().equals(""))
            {    JOptionPane.showMessageDialog(rootPane, "Debes agregar una materia", "MENSAJE DE ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        else if(!txtClMateria.getText().equals("") && !txtNbMateria.getText().equals("")){  
        try {
            // agregar
            // the mysql insert statement
            MySqlConnect mysqlConnect = new MySqlConnect();
            String query="";
            String message="";
            if(ID_MATERIA==0)
            {
                message="Se agrego una materia";
                query = " insert into c_materia (CL_MATERIA, NB_MATERIA)"
                    + " values (?, ?)";
                
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = mysqlConnect.connect().prepareStatement(query);
            preparedStmt.setString (1, txtClMateria.getText());
            preparedStmt.setString (2, txtNbMateria.getText());
            // execute the preparedstatement
            preparedStmt.execute();
            clear();
            }
            else 
            {
                message="Se edito la materia seleccionada";

                query = "update c_materia set NB_MATERIA = ? where ID_MATERIA = ?";
                PreparedStatement preparedStmt = mysqlConnect.connect().prepareStatement(query);
                preparedStmt.setString(1, txtNbMateria.getText());             
                preparedStmt.setInt(2, ID_MATERIA);
                 // execute the java preparedstatement
                 preparedStmt.executeUpdate();
                 clear();
                 txtClMateria.enable(true);
            }
            loadData();
            Icon image= new ImageIcon(getClass().getResource("/imagenes/correcto_sin_f.png"));
            JOptionPane.showMessageDialog(rootPane, message,"",JOptionPane.INFORMATION_MESSAGE,image);
            mysqlConnect.connect().close();
        } catch (SQLException ex) {
            Logger.getLogger(Materias.class.getName()).log(Level.SEVERE, null, ex);
        }
          }
         else 
        {
           
        }
         
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(ID_MATERIA!=0)
        {
            for (E_MATERIAS mat : materias) {
                if(mat.getID_MATERIA()==ID_MATERIA)
                {
                    txtClMateria.enable(false);
                    txtClMateria.setText(mat.getCL_MATERIA());                    
                    txtNbMateria.setText(mat.getNB_MATERIA());
                    break;
                }
            }
        }
        else 
        {
        Icon image= new ImageIcon(getClass().getResource("/imagenes/selecciona_sin_f.png"));
        JOptionPane.showMessageDialog(null, "Selecciona una materia","",JOptionPane.INFORMATION_MESSAGE,image);
        }
   
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        Menu refresh= new Menu();
//        refresh.setVisible(true);
        refresh.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         if(ID_MATERIA!=0)
            {
    int dialogButton = JOptionPane.YES_NO_OPTION;
    int dialogResult = JOptionPane.showConfirmDialog(this, "¿Desea eliminar la materia seleccionada?, Este proceso no se puede deshacer.", "Confirmar", dialogButton);
    if(dialogResult == 0) {
//  System.out.println("Yes option");
        try {
            MySqlConnect mysqlConnect = new MySqlConnect();
            String query="";
            String message="";
            
                   query = "delete from c_materia where ID_MATERIA = ?";
                  message="Se elimino la Materia";

                PreparedStatement preparedStmt = mysqlConnect.connect().prepareStatement(query);
                preparedStmt.setInt(1, ID_MATERIA);
                preparedStmt.execute();

            loadData();
            Icon image= new ImageIcon(getClass().getResource("/imagenes/borrar_sin_f.png"));
            JOptionPane.showMessageDialog(null, message,"",JOptionPane.INFORMATION_MESSAGE,image);
            mysqlConnect.connect().close();
        } catch (SQLException ex) {
            Logger.getLogger(Materias.class.getName()).log(Level.SEVERE, null, ex);
        }
}
            }
            else 
            {
            Icon image= new ImageIcon(getClass().getResource("/imagenes/selecciona_sin_f.png"));
            JOptionPane.showMessageDialog(null, "Selecciona una materia","",JOptionPane.INFORMATION_MESSAGE,image);
            }
                                    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Menu m= new Menu();
               m.setLocationRelativeTo(null);
                m.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableM;
    private javax.swing.JTextField txtClMateria;
    private javax.swing.JTextField txtNbMateria;
    // End of variables declaration//GEN-END:variables
}
