/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_cedva;

import Modelo.E_PROFESOR;
import Mysql.MySqlConnect;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import sistema_cedva.Asistencia;

/**
 *
 * @author P3DR1TO
 */
public class Profesor_Selected extends javax.swing.JFrame {
    
    ArrayList<E_PROFESOR> profesores= new ArrayList<E_PROFESOR>();
    int ID_PROFESOR = 0;
    String NB_PROFESOR;
        Asistencia pr;
    /**
     * Creates new form Usuarios
     */
    public Profesor_Selected(Asistencia pr) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Logo_JAR.png")).getImage());
        this.getContentPane().setBackground(Color.RED);
        this.setLocationRelativeTo(this);
        this.pr=pr;
        loadData();
    }
    
    
    public void loadData()
    {
        profesores.clear();
        ID_PROFESOR=0;
        
        MySqlConnect mysqlConnect = new MySqlConnect();
        Statement st;
        try {
            st = mysqlConnect.connect().createStatement();

        String sql = "SELECT * FROM c_profesor";
        ResultSet rs = st.executeQuery(sql);
        while(rs.next()) { 
        int idProfesor = rs.getInt("ID_PROFESOR"); 
        String clProfesor = rs.getString("CL_PROFESOR");
        String nbProfesor= rs.getString("NB_PROFESOR");
        profesores.add(new E_PROFESOR(idProfesor, clProfesor, nbProfesor));
        }
            } catch (SQLException ex) {
            Logger.getLogger(Profesor_Selected.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        mysqlConnect.disconnect();
        String col[] = {"Id","Clave","Nombre Profesor"};
        DefaultTableModel dtm = new DefaultTableModel(col, 0);
         for (E_PROFESOR s : profesores) {
         Object[] objs = {s.getID_PROFESOR(),s.getCL_PROFESOR(),s.getNB_PROFESOR()};
         dtm.addRow( objs);
         }
         
        jTableP.setModel(dtm);
        jTableP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTableP.getColumnModel().getColumn(0).setMaxWidth(0);

        jTableP.getColumnModel().getColumn(0).setMinWidth(0);

        jTableP.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        jTableP.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTableP.getColumnModel().getColumn(2).setPreferredWidth(400);
    }

        private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        
        // get the model from the jtable
       DefaultTableModel model = (DefaultTableModel)jTableP.getModel();
        // get the selected row index
       int selectedRowIndex = jTableP.getSelectedRow();
        // set the selected row data into jtextfields
       ID_PROFESOR =Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString()) ;   
       NB_PROFESOR=model.getValueAt(selectedRowIndex, 2).toString();   

    }   

    public void clear(){
//            txtClProfesor.setText(null);
//            txtNbProfesor.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableP = new javax.swing.JTable();
        btn_atras1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(695, 315));
        setMinimumSize(new java.awt.Dimension(695, 315));
        setPreferredSize(new java.awt.Dimension(695, 315));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Clave", "Profesor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableP.setEditingRow(1);
        jTableP.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableP.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableP);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 670, 220));

        btn_atras1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_atras1.setText("Seleccionar");
        btn_atras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atras1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_atras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 120, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_atras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atras1ActionPerformed
        if(ID_PROFESOR!=0)
            {       
//        APP_CONTEXTO.setNB_PROSPECTO(NB_PROSPECTO);    
//        APP_CONTEXTO.setID_PROSPECTO(ID_PROSPECTO);
        pr.setNbProfesor(NB_PROFESOR);
        pr.setIdProf(ID_PROFESOR);

        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
         
            }
            else 
        {
        Icon image= new ImageIcon(getClass().getResource("/imagenes/selecciona_sin_f.png"));
             JOptionPane.showMessageDialog(null, "Selecciona un profesor","",JOptionPane.INFORMATION_MESSAGE,image);
        }
    }//GEN-LAST:event_btn_atras1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableP;
    // End of variables declaration//GEN-END:variables
}
