/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_cedva;

import Modelo.E_ROLES;
import Mysql.MySqlConnect;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author P3DR1TO
 */
public class RolesSelected extends javax.swing.JFrame {
    
    ArrayList<E_ROLES> rol= new ArrayList<E_ROLES>();
    int ID_ROL = 0;
    String NB_ROL;
        Permisos r;

    /**
     * Creates new form Roles
     */
    public RolesSelected(Permisos r) {
        initComponents();
          this.r=r;
          setIconImage(new ImageIcon(getClass().getResource("/imagenes/Logo_JAR.png")).getImage());
          this.getContentPane().setBackground(Color.RED);
          this.setLocationRelativeTo(this);
          loadData();
    }  
    
    
    public void loadData()
    {
        rol.clear();
//        ID_ROLES=0;
        
        MySqlConnect mysqlConnect = new MySqlConnect();
        Statement st;
        try {
            st = mysqlConnect.connect().createStatement();

        String sql = "SELECT * FROM c_rol";
        ResultSet rs = st.executeQuery(sql);
        while(rs.next()) { 
        int idRol = rs.getInt("ID_ROL"); 
        String clRol = rs.getString("CL_ROL");
        String nbRol = rs.getString("NB_ROL");
        rol.add(new E_ROLES(idRol, clRol, nbRol));
        }
            } catch (SQLException ex) {
            Logger.getLogger(RolesSelected.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        mysqlConnect.disconnect();
        String col[] = {"Id","Clave","Nombre Rol"};
        DefaultTableModel dtm = new DefaultTableModel(col, 0);
         for (E_ROLES s : rol) {
         Object[] objs = {s.getID_ROL(),s.getCL_ROL(),s.getNB_ROL()};
         dtm.addRow( objs);
         }
         
        jTableR.setModel(dtm);
        jTableR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            
   
        });
     jTableR.getColumnModel().getColumn(0).setMaxWidth(0);

    jTableR.getColumnModel().getColumn(0).setMinWidth(0);

    jTableR.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

        private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        
        // get the model from the jtable
       DefaultTableModel model = (DefaultTableModel)jTableR.getModel();
        // get the selected row index
       int selectedRowIndex = jTableR.getSelectedRow();
        // set the selected row data into jtextfields
       ID_ROL =Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString()) ;       
       NB_ROL =model.getValueAt(selectedRowIndex, 2).toString();   
    }
        
        public void clear(){
//            txtClRol.setText(null);
//            txtNbRol.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableR = new javax.swing.JTable();
        btn_atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(815, 360));
        setMinimumSize(new java.awt.Dimension(815, 370));
        setPreferredSize(new java.awt.Dimension(800, 370));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Clave", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableR.setEditingRow(1);
        jTableR.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableR.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableR);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 270));

        btn_atras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_atras.setText("Seleccionar");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 120, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        r.setNbRol(NB_ROL);
        r.setIdRol(ID_ROL);
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btn_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableR;
    // End of variables declaration//GEN-END:variables
}
