/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_cedva;

import Modelo.E_USUARIO;
import Mysql.MySqlConnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.*;
import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author P3DR1TO
 */
public class Usuarios extends javax.swing.JFrame {
    
    ArrayList<E_USUARIO> usuarios= new ArrayList<E_USUARIO>();
    int ID_USUARIO ;
    String CL_USER;
    String NB_PASSWORD;
     /**
     * Creates new form Usuarios
     */
    
    
    public Usuarios() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Logo_JAR.png")).getImage());
        this.getContentPane().setBackground(Color.RED);
        this.setLocationRelativeTo(this);
        loadData();
        
    }
    
    
    public void loadData()
    {
        usuarios.clear();
        ID_USUARIO=0;
        
   MySqlConnect mysqlConnect = new MySqlConnect();
   Statement st;
        try {
            st = mysqlConnect.connect().createStatement();

String sql = "SELECT * FROM c_usuario";
ResultSet rs = st.executeQuery(sql);
while(rs.next()) { 
 int idUser = rs.getInt("ID_USER"); 
 String clUser = rs.getString("CL_USER");
 String nbPassword = rs.getString("NB_PASSWORD");
 boolean fgActivo = rs.getBoolean("FG_ACTIVO");
 usuarios.add(new E_USUARIO(idUser, clUser, nbPassword, fgActivo, (fgActivo)?"Si":"No"));
}
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        


mysqlConnect.disconnect();
String col[] = {"Id","Usuario","Password","Activo"};
    DefaultTableModel dtm = new DefaultTableModel(col, 0);
    for (E_USUARIO s : usuarios) {
         Object[] objs = {s.getID_USER(),s.getCL_USER(),s.getNB_PASSWORD(),s.getCL_ACTIVO()};
         dtm.addRow( objs);
    }

   
    jTable1.setModel(dtm);
       jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });

    jTable1.getColumnModel().getColumn(0).setMaxWidth(0);

    jTable1.getColumnModel().getColumn(0).setMinWidth(0);

    jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        
        // get the model from the jtable
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        // get the selected row index
       int selectedRowIndex = jTable1.getSelectedRow();
        // set the selected row data into jtextfields
       ID_USUARIO =Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString()) ;       

    }
    
//     public void validar(){
//            if(txtClUser.getText().equals("")){
//            JOptionPane.showMessageDialog(jTable1, "Debes agregar un usuario y contraseña", "Debes agregar un usuario y contraseña", JOptionPane.ERROR_MESSAGE);
//            }
//    }

    public void clear(){
            txtClUser.setText(null);
            txtNbPassword.setText(null);
            chkActivo.setSelected(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtClUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNbPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        chkActivo = new javax.swing.JCheckBox();
        btn_atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(835, 350));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        btn_edit.setText("Editar");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Usuario", "Password", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEditingRow(1);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 800, 90));

        txtClUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClUserActionPerformed(evt);
            }
        });
        getContentPane().add(txtClUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));
        getContentPane().add(txtNbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Activo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));
        getContentPane().add(chkActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        btn_atras.setText("Regresar");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtClUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        if (txtClUser.getText().equals("") && txtNbPassword.getText().equals(""))
            {         
                JOptionPane.showMessageDialog(rootPane, "Debes agregar un usuario y contraseña", "MENSAJE DE ADVETENCIA", JOptionPane.WARNING_MESSAGE);
            }
        else if (txtClUser.getText().equals(""))
            {    JOptionPane.showMessageDialog(rootPane, "Debes agregar un usuario", "MENSAJE DE ADVETENCIA", JOptionPane.WARNING_MESSAGE);
            }
        else if (txtNbPassword.getText().equals(""))
            {    JOptionPane.showMessageDialog(rootPane, "Debes agregar una contraseña", "MENSAJE DE ADVETENCIA", JOptionPane.WARNING_MESSAGE);
            }
        else if(!txtClUser.getText().equals("") && !txtNbPassword.getText().equals("")){
        try {
            // agregar
            // the mysql insert statement
            MySqlConnect mysqlConnect = new MySqlConnect();
            String query="";
            String message="";
            if(ID_USUARIO==0)
            {
                message="Se agrego usuario de manera adecuada";
                query = " insert into c_usuario (CL_USER, NB_PASSWORD, FG_ACTIVO)"
                    + " values (?, ?, ?)";
                
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = mysqlConnect.connect().prepareStatement(query);
            preparedStmt.setString (1, txtClUser.getText());
            preparedStmt.setString (2, txtNbPassword.getText());
            preparedStmt.setBoolean(3, chkActivo.isSelected());
            // execute the preparedstatement
            preparedStmt.execute();
            clear();
            }
            else 
            {
                message="Se edito usuario de manera exitosa";

                query = "update c_usuario set NB_PASSWORD = ?, FG_ACTIVO = ? where ID_USER = ?";
                PreparedStatement preparedStmt = mysqlConnect.connect().prepareStatement(query);
                preparedStmt.setString(1, txtNbPassword.getText());
                preparedStmt.setBoolean(2, chkActivo.isSelected());               
                preparedStmt.setInt(3, ID_USUARIO);
                 // execute the java preparedstatement
                 preparedStmt.executeUpdate();
                clear();
                txtClUser.enable(true);
            }
            loadData();
//            JOptionPane.showMessageDialog(rootPane,message );
            Icon image= new ImageIcon(getClass().getResource("/imagenes/correcto_sin_f.png"));
            JOptionPane.showMessageDialog(rootPane, message,"",JOptionPane.INFORMATION_MESSAGE,image);
            mysqlConnect.connect().close();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
        else 
        {
//            JOptionPane.showMessageDialog(jTable1, "Debes agregar un usuario y contraseña", "Debes agregar un usuario y contraseña", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        
        if(ID_USUARIO!=0)
        {
            for (E_USUARIO usuario : usuarios) {
                if(usuario.getID_USER()==ID_USUARIO)
                {   
                    txtClUser.enable(false);
                    txtClUser.setText(usuario.getCL_USER());                    
                    txtNbPassword.setText(usuario.getNB_PASSWORD());
                    chkActivo.setSelected(usuario.getFG_ACTIVO());
                    break;
                }
            }
        }
        else 
        {
        Icon image= new ImageIcon(getClass().getResource("/imagenes/selecciona_sin_f.png"));
        JOptionPane.showMessageDialog(null, "Selecciona un usuario","",JOptionPane.INFORMATION_MESSAGE,image);
        }
   
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
         Menu regresar= new Menu();
//        refresh.setVisible(true);
        dispose();
        regresar.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
         if(ID_USUARIO!=0)
            {
int dialogButton = JOptionPane.YES_NO_OPTION;
int dialogResult = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el usuario seleccionado?, Este proceso no se puede deshacer.", "Confirmar", dialogButton);
if(dialogResult == 0) {
//  System.out.println("Yes option");
        try {
            MySqlConnect mysqlConnect = new MySqlConnect();
            String query="";
            String message="";
            
                   query = "delete from c_usuario where ID_USER = ?";
                  message="Se elimino el usuario";

                PreparedStatement preparedStmt = mysqlConnect.connect().prepareStatement(query);
                preparedStmt.setInt(1, ID_USUARIO);
                preparedStmt.execute();

            loadData();
             Icon image= new ImageIcon(getClass().getResource("/imagenes/borrar_sin_f.png"));
             JOptionPane.showMessageDialog(null, message,"",JOptionPane.INFORMATION_MESSAGE,image);
            mysqlConnect.connect().close();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "No puedes eliminar un usuario que tiene asignado Roles", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
        }
}
            }
            else 
            {
            Icon image= new ImageIcon(getClass().getResource("/imagenes/selecciona_sin_f.png"));
            JOptionPane.showMessageDialog(null, "Selecciona un permiso","",JOptionPane.INFORMATION_MESSAGE,image);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Menu m= new Menu();
               m.setLocationRelativeTo(null);
                m.setVisible(true);
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_edit;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtClUser;
    private javax.swing.JPasswordField txtNbPassword;
    // End of variables declaration//GEN-END:variables
}
